config/routes.rb
Rails.application.routes.draw do
  root "users#index"
  resources :freindships
  resources :users
  resource :session, only: [:new, :create, :destroy]
  get "follow" => "freindships#create"
  get "accept" => "freindships#update"
  get "unfollow" => "freindships#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/freindship.rb
class Freindship < ApplicationRecord
  belongs_to :user
  belongs_to :freind, class_name:  'User', foreign_key: 'freind_id'

  validates :status, :user_id, :freind_id, presence: true
  validates :status, inclusion: {in:  %w(accepted pending requested)}
  validates :user_id, uniqueness: { scope: :freind_id, messages: "! You Already send !" }
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :freindships, dependent: :destroy
  has_many :freinds, -> {where(freindships: {status: "accepted"}) },through: :freindships
  has_many :pending_freinds, -> {where(freindships: {status: "pending"}) },through: :freindships, source: :freind
  has_many :requested_freinds, -> {where(freindships: {status: "requested"}) },through: :freindships, source: :freind

  validates :email, uniqueness:true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

  def current_user?(user)
    current_user == user
  end

  helper_method :current_user?

  def user_status(user)
    @freindship = Freindship.find_by(user_id: current_user.id, freind_id: user.id )
    if !@freindship.nil?
       @freindship.status
    end
  end

  helper_method :user_status
  
end

app/controllers/freindships_controller.rb
class FreindshipsController < ApplicationController

  def create
    @freindship1 = Freindship.new(status: params[:status1], user_id:  params[:freind], freind_id: current_user.id)
    @freindship2 = Freindship.new(status: params[:status2], user_id:  current_user.id, freind_id: params[:freind])
    if (@freindship1.save & @freindship2.save)
      redirect_to root_path, notice: "Freind Request is Sent !"
    else
      redirect_to root_path , notice: "You Already sent !"
    end
  end

    def update
      @freindship1 = Freindship.find_by(user_id: current_user.id, freind_id: params[:freind])
      @freindship2 = Freindship.find_by(user_id: params[:freind], freind_id: current_user.id)
      @freindship1.status = params[:status1]
      @freindship2.status = params[:status2]
      if (@freindship1.save & @freindship2.save)
        redirect_to current_user
      end
    end

    def destroy 
      @freindship1 = Freindship.find_by(user_id: current_user.id, freind_id: params[:freind])
      @freindship2 = Freindship.find_by(user_id: params[:freind], freind_id: current_user.id)
      @freindship2.destroy
      if  (@freindship1.destroy)
        redirect_to current_user, notice: "Request Deleted !"
      else
        redirect_to current_user, notice: "Unable To Delete Request"
      end
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new 
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to user
    else
      render :new
    end
  end

  def destroy 
    session[:user_id] = nil
    redirect_to users_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new 
    @user = User.new
  end

  def show 
    @user = User.find(params[:id])
    @freinds = @user.freinds
    @requests = @user.requested_freinds
    @pending = @user.pending_freinds
  end

  def edit 
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to users_url
    else
      render :new, notice: "Unable To Update Your Account"
    end
  end

  def destroy
    @user = User.find(params[:id])
    if @user.destroy
      session[:user_id] = nil
      redirect_to users_url
    else
      redirect_to root_path, notice: "Unable To Delete Your Account"
    end
  end

  def create 
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to @user
    else
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/freindships_helper.rb
module FreindshipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_flash.html.erb
<% flash.each do |type, message| %>
  <%= content_tag(:div, message, class: "flash #{type}") %>
<% end %>

app/views/layouts/_header.html.erb
<header>
  <nav>
    <%= link_to "FACEBOOK!", root_path %>

     <ul class="right">
      <% if current_user %>
        <li><%= link_to current_user.name, current_user%></li>
        <li><%= link_to "Sign Out", session_path, method: :delete, class: "button"%></li>
      <% else %>
        <li>
         <%= link_to "Sign Up", new_user_path, class: "button" %>
         <%= link_to "Sign In", new_session_path, class: "button" %>
        </li>
      <%end%>
    </ul>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Facebook</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>
    
    <div class="content">
      <%= render "layouts/flash" %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/users/_errors.html.erb
<% if object.errors.any? %>
  <section class="errors">
    <h2>
      Oops! Your form could not be saved.
    </h2>
    <h3>
      Please correct the following
      <%= pluralize(object.errors.size, "error") %>:
    </h3>
    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </section>
<% end %>

app/views/users/_form.html.erb
<%= form_with(model: user, local:true) do |f|%>
<%= render "errors", object: user%>

<%= f.label :name %> 
<%= f.text_field(:name)%> 

<%= f.label(:email)%>
<%= f.text_field(:email)%>

<%= f.label(:password)%>
<%= f.text_field(:password)%>

<%= f.label(:password_confirmation)%>
<%= f.text_field(:password_confirmation)%>

<% if user.new_record? %>
  <%= f.submit  "Create Account"  %>
<%else%>
   <%= f.submit  "Update Account"  %>
<%end%>
<%end%>

app/views/users/edit.html.erb
<h1>Edit Your Account</h1>
<%= render "form", user: @user%>

app/views/users/index.html.erb
<h1  style="text-align:center"> Welcome To Facebook ! </h1>
<%if current_user%>
  <ul style= "test-align:center">
    <h2> Users using Facebook ! </h2>
    <% @users.each do  |user| %>
      <% if user_status(user) == "accepted"%>
          <li> <%=link_to user.name, user  %> ->   <%= link_to "UnFollow", unfollow_url(@invoice, :freind => user.id) %> </li>
      <%elsif user_status(user) == "requested"%>
          <li> <%=link_to user.name, user  %> -><%= link_to "Accept", accept_url(@invoice, :status1 => "accepted", :status2 => "accepted",:freind => user.id) %>
           <%= link_to "Delete", unfollow_url(@invoice, :freind => user.id) %>
      <% elsif user_status(user) == "pending"%>
        <li> <%=link_to user.name, user  %> ->   <%= link_to "Undo", unfollow_url(@invoice, :freind => user.id) %> </li>
      <% else%>
        <li> <%=link_to user.name, user  %> -> <%= link_to "Follow", follow_url(@invoice, :status1 => "requested", :status2 => "pending", :freind => user.id) %> </li>
      <%end%>
    <% end %>
  </ul>
<%else%>
    <div style="text-align:center"> ! Please open Your Account Or Sign iN First ! </div>
  
<%end%>
  

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= render "form", user: @user%>

app/views/users/show.html.erb
<section class="user"  style="text-align:center">
  <h1><%= @user.name %></h1>
  <h2><%= mail_to(@user.email) %></h2>
  <div class="actions">
    <%if current_user?(@user)%>
      <%= link_to "Edit Account", edit_user_path(@user), class: "button edit" %>
      <%= link_to 'Delete Account', @user, method: :delete,
                   data: { confirm: "Permanently delete your account!?" },
                   class: "button delete" %>
    <%end%> 
  </div>
</section>


  <% if !@freinds.empty? %>
    <h2> <i> Freind List </i> </h2>
    <% @freinds.each do |freind| %>
      <li>
        <%=link_to freind.name, freind %> : <%=freind.email%> 
        <%= link_to "UnFollow", unfollow_url(@invoice, :freind => freind.id) %>
      </li>
    <%end%>
  <% else %>
    <h2> No Freinds ! </h2>
  <%end%>

  <% if (current_user?(@user) & !@requests.empty?) %>
    <h2> <i> Freind Request </i> </h2>
    <% @requests.each do |request| %>
      <li>
        <%=link_to request.name, request %> : <%=request.email%>
        <%= link_to "Accept", accept_url(@invoice, :status1 => "accepted", :status2 => "accepted",:freind => request.id) %>
        <%= link_to "Delete", unfollow_url(@invoice, :freind => request.id) %>
      </li>
    <%end%>
  <%else%>
    <h2> 0 Request ! </h2> mmmmmmm
  <%end%>

  <% if (current_user?(@user) & !@pending.empty?) %>
    <h2> <i> ! People, You sent request ! </i> </h2>
    <% @pending.each do |pen| %>
      <li>
        <%=link_to pen.name, pen %> : <%=pen.email%>
        <%= link_to "undo", unfollow_url(@invoice, :freind => pen.id) %>
      </li>
    <%end%>
  <%else%>
    <h2> 0 Request ! </h2>
  <%end%>